# .github/workflows/terraform.yml
name: Terraform Infrastructure CI/CD

on:
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action (plan or apply)'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
  # Optional: Trigger on pushes to a specific branch containing infrastructure code
  # push:
  #   branches:
  #     - infra # Or your chosen branch for infrastructure changes
  #   paths:
  #     - '**.tf'
  #     - 'backend.tf' # Add backend file if using

# Grant permissions for the GITHUB_TOKEN (if needed for other steps, not TF Cloud)
permissions:
  contents: read # Read is usually sufficient unless pushing code

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.terraform_action || 'Plan' }}' # Dynamic job name
    runs-on: ubuntu-latest
    # Remove top-level env vars for TF_VARs, manage them in TFC UI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        # Configure Terraform Cloud credentials via token
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      # No DO_TOKEN needed here, backend config handles auth via TF_API_TOKEN
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      # Env vars (TF_VAR_*) are injected by Terraform Cloud based on workspace variables
      # DIGITALOCEAN_TOKEN is also typically set as an Environment Variable in TFC workspace
      run: terraform plan -no-color
      # Optional: Add '-out=tfplan' if needed

    # --- Apply Step - Only runs if manually triggered with 'apply' ---
    - name: Terraform Apply
      id: apply
      # Only run if the workflow was manually dispatched with input 'apply'
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_action == 'apply'
      # Env vars (TF_VAR_*) are injected by Terraform Cloud based on workspace variables
      # DIGITALOCEAN_TOKEN is also typically set as an Environment Variable in TFC workspace
      run: terraform apply -auto-approve -no-color
      # If using saved plan: run: terraform apply -auto-approve tfplan