name: Terraform Infrastructure CI/CD

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action (plan or apply)'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply

permissions:
  contents: write

jobs:
  terraform:
    # --- SIMPLIFIED STATIC JOB NAME ---
    name: Terraform Plan or Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_app_name: "job-app"
      TF_VAR_app_region: "lon1"
      TF_VAR_production_branch: "production"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        # Configure Terraform Cloud credentials via token
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_repo_path: ${{ secrets.TF_VAR_repo_path }}
        TF_VAR_database_url_prod: ${{ secrets.TF_VAR_database_url_prod }}
        TF_VAR_flask_secret_key_prod: ${{ secrets.TF_VAR_flask_secret_key_prod }}
        TF_VAR_adzuna_app_id: ${{ secrets.TF_VAR_adzuna_app_id }}
        TF_VAR_adzuna_app_key: ${{ secrets.TF_VAR_adzuna_app_key }}
        TF_VAR_azure_ai_endpoint: ${{ secrets.TF_VAR_azure_ai_endpoint }}
        TF_VAR_azure_ai_key: ${{ secrets.TF_VAR_azure_ai_key }}
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_action == 'apply'
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_repo_path: ${{ secrets.TF_VAR_repo_path }}
        TF_VAR_database_url_prod: ${{ secrets.TF_VAR_database_url_prod }}
        TF_VAR_flask_secret_key_prod: ${{ secrets.TF_VAR_flask_secret_key_prod }}
        TF_VAR_adzuna_app_id: ${{ secrets.TF_VAR_adzuna_app_id }}
        TF_VAR_adzuna_app_key: ${{ secrets.TF_VAR_adzuna_app_key }}
        TF_VAR_azure_ai_endpoint: ${{ secrets.TF_VAR_azure_ai_endpoint }}
        TF_VAR_azure_ai_key: ${{ secrets.TF_VAR_azure_ai_key }}
      run: terraform apply -auto-approve -no-color
