# .github/workflows/terraform.yml
name: Terraform Infrastructure CI/CD

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action (plan or apply)'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply

permissions:
  contents: read # Read is sufficient as TFC token handles auth to TFC

jobs:
  terraform:
    name: Terraform Plan or Apply
    runs-on: ubuntu-latest
    # Environment variables set here are for the runner's environment.
    # Terraform Cloud will inject workspace variables (TF_VAR_* and Environment Variables like DIGITALOCEAN_TOKEN)
    # when it executes the plan/apply.
    env:
      # This is primarily for the DigitalOcean provider to authenticate during 'terraform init'
      # if it needs to access the DO API before TFC fully takes over the run.
      # Ensure DIGITALOCEAN_TOKEN is also set as an Environment Variable in your TFC workspace.
      DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        # This token allows the runner to authenticate to Terraform Cloud
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      # The DIGITALOCEAN_TOKEN from the job's env block will be available for 'terraform init'.
      # Terraform Cloud backend configuration in your .tf files will take over from here.
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      # All TF_VAR_* variables (like TF_VAR_ssh_key_name, TF_VAR_repo_path, etc.)
      # are now expected to be set in the Terraform Cloud workspace
      # (either directly or via an applied Variable Set)
      # and will be automatically available to this command when run by TFC.
      # The DIGITALOCEAN_TOKEN for provider auth should also be set as an Environment Variable in TFC.
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_action == 'apply'
      # All TF_VAR_* variables and provider auth (DIGITALOCEAN_TOKEN)
      # are expected to be set in the Terraform Cloud workspace.
      run: terraform apply -auto-approve -no-color
